name: MailChimp Get Donors

on: 
  workflow_dispatch:

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Gets donors
    steps:
      - name: Get Donors
        uses: musicatstalbans/MailChimpGetDonors@main
        with:
          mailchimp-list-id: ${{ secrets.MAILCHIMP_LIST_ID }}
          mailchimp-segment-id: ${{ secrets.MAILCHIMP_SEGMENT_ID }}
          mailchimp-token: ${{ secrets.MAILCHIMP_TOKEN }}
          mailchimp-server-prefix: ${{ secrets.MAILCHIMP_SERVER_PREFIX }}